name: Package Watch the Skies
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ARCHIVE_NAME: Watch_the_Skies_${{github.ref_name}}
    steps:

      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 50
          
      - name: Prune files
        run: |
          rm -f README.md
          mv .git ../temp
          mv .github ../temp
          ls -a
          
      - name: Build Project
        uses: edgarrc/action-7z@v1
        with:
          args: 7z a  ${{env.ARCHIVE_NAME}}.7z
          
      - name: Restore git files
        run: |
          ls -a
          mv ../temp/.git .
          mv ../temp/.github .

      - name: Create Release
        uses: notlmn/release-with-changelog@v2
        with:
          header: '### Changelog'
          include-hash: true
          include-range: true
          token: ${{secrets.GITHUB_TOKEN}}

      - name: Upload to Github
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          files: ${{env.ARCHIVE_NAME}}.7z
